/*USUARIOS*/
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('vigueras.andrea', 'vigueras.andrea', NULL, '201701001', '$2y$12$GHzS.mZk8aST4dJmbrrub.oSLSrKAjSc7yvjPV5kUxpLXttrrKKBG', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('romero.violeta', 'romero.violeta', NULL, '201701005', '$2y$12$ne.QizuvSnVUub15DSLwt.lIcROoAC3Z7X4x3pWIUVrLPaU7NdqSq', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('hernandez.gerardo', 'hernandez.gerardo', NULL, '201701007', '$2y$12$zYMFGHA7Vnw.otUxKS3o2.Ou7nEL655v/nCPC3TOKM3OpHPR6ruOC', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('rivera.maria', 'rivera.maria', NULL, '201701011', '$2y$12$tayXFWJ0yuMBgCEg402k8uFM1Z/1w4VBaxOk3fa1NAQANHnmO8hRe', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('santiago.jose', 'santiago.jose', NULL, '201701013', '$2y$12$vicSxRILOwJY6700FIDSx.prVQB70K4tZrOF28GfyQLDg0C5Zgu/K', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('santiago.beatriz', 'santiago.beatriz', NULL, '201701012', '$2y$12$v6trJKfQsFeb82RTEllC5uTYkPyJ06SioBRa4XtzQH0rWLx5YXaxC', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('mendez.isai', 'mendez.isai', NULL, '201704001', '$2y$12$bHZV1NUvjVTu9Jm4g47EyOWNGYglLWagNNFWJYgXsvgg7litpdcA.', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('hernandez.erika', 'hernandez.erika', NULL, '201704002', '$2y$12$u9r2tc5oszuIOR7UjOHVnecirmWLm8HykXqD.gKsgYgyaNbHCKqcC', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('olarte.oliver', 'olarte.oliver', NULL, '201704003', '$2y$12$euQ/e7UKBoVN.tZ5.vYyM.H0VuwWwHoE.k1IoFK9231QfrjXATdAG', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('galindo.marlene', 'galindo.marlene', NULL, '201704004', '$2y$12$/j0UxmWn9WSbgEP7OPHI4.C/.XwtrQz4RX1z.Ejz3VKHsXpXfOtY2', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('alvarez.lizbeth', 'alvarez.lizbeth', NULL, '201704005', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('garcia.marisol', 'garcia.marisol', NULL, '201704009', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('martin.clara', 'martin.clara', NULL, '201704008', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('garcia.morales.dario', 'garcia.morales.dario', NULL, '201705001', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('robles.luis', 'robles.luis', NULL, '201705002', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('bautista.sandra', 'bautista.sandra', NULL, '20160202006', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('carrillo.omar', 'carrillo.omar', NULL, '201602001', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('islas.camilo', 'islas.camilo', NULL, '201602002', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('zamora.irbin', 'zamora.irbin', NULL, '201602003', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('zamora.sujey', 'zamora.sujey', NULL, '201602004', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('manzano.alejandro', 'manzano.alejandro', NULL, '201602007', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('mora.elizabeth', 'mora.elizabeth', NULL, '201604002', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('meneses.aaron', 'meneses.aaron', NULL, '201604004', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('montes.mariana', 'montes.mariana', NULL, '20160102001', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('benitez.andrea', 'benitez.andrea', NULL, '20160102008', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('guerra.erika', 'guerra.erika', NULL, '20160102006', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('amador.jose', 'amador.jose', NULL, '20160102007', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('tapia.ariel', 'tapia.ariel', NULL, '20160102011', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('aponte.melissa', 'aponte.melissa', NULL, '20160102012', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('chantes.gustavo', 'chantes.gustavo', NULL, '20160102014', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('marin.oscar', 'marin.oscar', NULL, '201401006', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('fragoso.sergio', 'fragoso.sergio', NULL, '20160102013', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('romero.rey', 'romero.rey', NULL, '201605001', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('ortiz.carlos', 'ortiz.carlos', NULL, '201605005', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('luna.noemi', 'luna.noemi', NULL, '20160402013', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('baez.jose', 'baez.jose', NULL, '201603001', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('morales.jose', 'morales.jose', NULL, '201603002', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('perez.lizethbet', 'perez.lizethbet', NULL, '201603008', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('olivares.genesis', 'olivares.genesis', NULL, '201603005', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('cruz.landy', 'cruz.landy', NULL, '201601002', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('sanchez.angelica', 'sanchez.angelica', NULL, '201601004', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('carmona.angelica', 'carmona.angelica', NULL, '201601006', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('flores.alma', 'flores.alma', NULL, '201601008', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('gomez.israel', 'gomez.israel', NULL, '201504001', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('ibanez.daniel', 'ibanez.daniel', NULL, '201504003', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('rojas.leticia', 'rojas.leticia', NULL, '201504006', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('cancino.carmina', 'cancino.carmina', NULL, '201504009', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('romero.maria', 'romero.maria', NULL, '201504010', '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('carmona.leopoldo', 'carmona.leopoldo', NULL, '201501003', '', NULL, NULL, NULL);

/*PROFESORES*/
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('adolfo.emanuel.hernandez', 'adolfo.emanuel.hernandez', 1, NULL, '$2y$12$65U/qSeGhbQbMno1Wmmyt.xO.zFIyen5Gv8WO34DmhNw01GCvsn3O', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('adriana.liliana.cercado', 'adriana.liliana.cercado', 2, NULL, '$2y$12$ePfCLKAhTP8M7SnIhBckL.xp8duM3vjke..hgi4OhNyhNutYUacY.', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('alberto.flores', 'alberto.flores', 3, NULL, '$2y$12$4bgnqgdht.ybA9Z1djPZz.Tnf02YiHn/B3r7wlYqzlZgh4gkSC7Xa', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('aldo.benitez', 'aldo.benitez', 4, NULL, '$2y$12$9vm4/GfeBCAGNclToiR9uuvNvnb9D7t6AMb4g.fb1PHDT33IXyqry', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('carlos.alberto.lopez', 'carlos.alberto.lopez', 5, NULL, '$2y$12$iDMLYxMS5bUPG7ktbQA4U.0OylbbRWMAbrsMM3B5X7Mk.FkuTMnMy', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('christian.israel.rodriguez', 'christian.israel.rodriguez', 6, NULL, '$2y$12$iGxSERwChUDril1lRK8Vpe/NYk.nyK56Vzsj6fB1PZvq8743j4mSO', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('fiorela.benitez', 'fiorela.benitez', 7, NULL, '$2y$12$ViCT9TmLXA9BgHWXmmgWZu0/7XI4MDQLEOhokBGZPHdz2uKtUbj1G', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('francisco.maldonado', 'francisco.maldonado', 8, NULL, '$2y$12$TOtX794vWqmOWWHLNm3v.OhptaMSnocRPukxjYsVNKvxIfR6zKEBm', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('gregorio.cruz', 'gregorio.cruz', 9, NULL, '$2y$12$KBxZnV2lnAGzBRobl3loYOBWQq84ZrCIJIfdvdSiMdufsQ.F/EC8W', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('guillermo.contreras', 'guillermo.contreras', 10, NULL, '$2y$12$eHCvf0eyqAxuXeyaLlY9xe/esQX1WXLNqk/DYmbE/pyz0JdnQdXpi', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('hortensia.coyotl', 'hortensia.coyotl', 11, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('isabel.machorro', 'isabel.machorro', 12, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('jose.antonio.aguas', 'jose.antonio.aguas', 13, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('jose.manuel.manuel', 'jose.manuel.manuel', 14, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('juan.jesus.limon', 'juan.jesus.limon', 15, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('julio.fernando.alvarado', 'julio.fernando.alvarado', 16, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('laura.carvajal', 'laura.carvajal', 17, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('lizandro.rios', 'lizandro.rios', 18, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('maria.elena.sanchez', 'maria.elena.sanchez', 19, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('nan.josedelacueva', 'nan.josedelacueva', 20, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('porfirio.rosete', 'porfirio.rosete', 21, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('raymundo.maldonado', 'raymundo.maldonado', 22, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('roberto.brambila', 'roberto.brambila', 23, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('tomas.israel.vazquez', 'tomas.israel.vazquez', 24, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('viridiana.lozada', 'viridiana.lozada', 25, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('waldo.guerrero', 'waldo.guerrero', 26, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('yara.lesly.hernandez', 'yara.lesly.hernandez', 27, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('alejandro.garcia', 'alejandro.garcia', 28, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('ariadna.ayala', 'ariadna.ayala', 29, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('gerardo.torres', 'gerardo.torres', 30, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('javier.chacon', 'javier.chacon', 31, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('francisco.garcia', 'francisco.garcia', 32, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('juan.rodriguez', 'juan.rodriguez', 33, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('rosario.rojas', 'rosario.rojas', 34, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('salvador.nunez', 'salvador.nunez', 35, NULL, '', NULL, NULL, NULL);
INSERT INTO `users` (`name`, `email`, `id_clave`, `id_alumn`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('daniel.calixto', 'daniel.calixto', 36, NULL, '', NULL, NULL, NULL);
/*ROLES*/

INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '2');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '3'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '4'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '5'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '6'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '7'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '8'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '9'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '10'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '11'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '12'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '13'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '14'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '15'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '16'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '17'); 
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '18');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '19');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '20');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '21');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '22');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '23');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '24');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '25');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '26');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '27');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '28');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '29');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '30');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '31');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '32');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '33');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '34');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '35');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '36');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '37');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '38');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '39');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '40');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '41');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '42');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '43');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '44');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '45');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '46');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '47');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '48');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '49');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('3', '50');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '51');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '52');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '53');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '54');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '55');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '56');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '57');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '58');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '59');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '60');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '61');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '62');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '63');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '64');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '65');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '66');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '67');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '68');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '69');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '70');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '71');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '72');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '73');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '74');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '75');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '76');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '77');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '78');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '79');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '80');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '81');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '82');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '83');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '84');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '85');
INSERT INTO `role_user` (`rol_id`, `user_id`) VALUES ('2', '86');